export const authorConstants = {

    GET_LIST_OF_AUTHORS_REQUEST: 'GET_LIST_OF_AUTHORS_REQUEST',
    GET_LIST_OF_AUTHORS_SUCCESS: 'GET_LIST_OF_AUTHORS_SUCCESS',
    GET_LIST_OF_AUTHORS_FAILURE: 'GET_LIST_OF_AUTHORS_FAILURE',

    CREATE_AUTHOR_REQUEST: 'CREATE_AUTHOR_REQUEST',
    CREATE_AUTHOR_SUCCESS: 'CREATE_AUTHOR_SUCCESS',
    CREATE_AUTHOR_FAILURE: 'CREATE_AUTHOR_FAILURE',

    SET_CURRENT_AUTHOR_LAST_NAME: 'SET_CURRENT_AUTHOR_LAST_NAME',
    SET_CURRENT_AUTHOR_FIRST_NAME: 'SET_CURRENT_AUTHOR_FIRST_NAME',
    SET_CURRENT_AUTHOR_PATRONYMIC: 'SET_CURRENT_AUTHOR_PATRONYMIC',

    RESET_AUTHOR_INFO: 'RESET_AUTHOR_INFO'
}