export const bookConstants = {
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAILURE: 'CREATE_BOOK_FAILURE',
    CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',

    GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
    GET_BOOK_FAILURE: 'GET_BOOK_FAILURE',
    GET_BOOK_REQUEST: 'GET_BOOK_REQUEST',

    GET_LIST_OF_BOOKS_REQUEST: 'GET_LIST_OF_BOOKS_REQUEST',
    GET_LIST_OF_BOOKS_SUCCESS: 'GET_LIST_OF_BOOKS_SUCCESS',
    GET_LIST_OF_BOOKS_FAILURE: 'GET_LIST_OF_BOOKS_FAILURE',

    GET_LIST_OF_FREE_BOOKS_REQUEST: 'GET_LIST_OF_FREE_BOOKS_REQUEST',
    GET_LIST_OF_FREE_BOOKS_SUCCESS: 'GET_LIST_OF_FREE_BOOKS_SUCCESS',
    GET_LIST_OF_FREE_BOOKS_FAILURE: 'GET_LIST_OF_FREE_BOOKS_FAILURE',

    GET_LIST_OF_BOOKS_BY_TITLE_REQUEST: 'GET_LIST_OF_BOOKS_BY_TITLE_REQUEST',
    GET_LIST_OF_BOOKS_BY_TITLE_SUCCESS: 'GET_LIST_OF_BOOKS_BY_TITLE_SUCCESS',
    GET_LIST_OF_BOOKS_BY_TITLE_FAILURE: 'GET_LIST_OF_BOOKS_BY_TITLE_FAILURE',

    GET_LIST_OF_BOOKS_BY_AUTHOR_REQUEST: 'GET_LIST_OF_BOOKS_BY_AUTHOR_REQUEST',
    GET_LIST_OF_BOOKS_BY_AUTHOR_SUCCESS: 'GET_LIST_OF_BOOKS_BY_AUTHOR_SUCCESS',
    GET_LIST_OF_BOOKS_BY_AUTHOR_FAILURE: 'GET_LIST_OF_BOOKS_BY_AUTHOR_FAILURE',

    GET_LIST_OF_BOOKS_BY_YEAR_REQUEST: 'GET_LIST_OF_BOOKS_BY_YEAR_REQUEST',
    GET_LIST_OF_BOOKS_BY_YEAR_SUCCESS: 'GET_LIST_OF_BOOKS_BY_YEAR_SUCCESS',
    GET_LIST_OF_BOOKS_BY_YEAR_FAILURE: 'GET_LIST_OF_BOOKS_BY_YEAR_FAILURE',

    SET_CURRENT_BOOK_ID: 'SET_CURRENT_BOOK_ID',
    SET_CURRENT_BOOK_TITLE: 'SET_CURRENT_BOOK_TITLE',
    SET_CURRENT_BOOK_AUTHOR_ID: 'SET_CURRENT_BOOK_AUTHOR_ID',
    SET_CURRENT_BOOK_YEAR: 'SET_CURRENT_BOOK_YEAR',
    SET_CURRENT_BOOK_COVER: 'SET_CURRENT_BOOK_COVER',
    SET_CURRENT_BOOK_IMAGE: 'SET_CURRENT_BOOK_IMAGE',
    SET_CURRENT_BOOK_COPIES_COUNT: 'SET_CURRENT_BOOK_COPIES_COUNT',
    SET_CURRENT_SWITCH_STATE: 'SET_CURRENT_SWITCH_STATE',

    SHOW_BOOK_REQUEST: 'SHOW_HOTEL_REQUEST',
    SHOW_BOOK_SUCCESS: 'SHOW_HOTEL_SUCCESS',
    SHOW_BOOK_FAILURE: 'SHOW_HOTEL_FAILURE',

    HIDE_BOOK: 'HIDE_BOOK',

    RESET_CURRENT_PAGE: 'RESET_CURRENT_PAGE',
    RESET_FILTER: 'RESET_FILTER',
    RESET_BOOK_INFO: 'RESET_BOOK_INFO'
}