export const commentConstants = {
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',

    GET_BOOK_COMMENTS_SUCCESS: 'GET_BOOK_COMMENTS_SUCCESS',
    GET_BOOK_COMMENTS_FAILURE: 'GET_BOOK_COMMENTS_FAILURE',
    GET_BOOK_COMMENTS_REQUEST: 'GET_BOOK_COMMENTS_REQUEST',

    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',
    DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',

    SET_CURRENT_COMMENT_TEXT: 'SET_CURRENT_COMMENT_TEXT'
}