export const reservationConstants = {
    GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_REQUEST: 'GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_REQUEST',
    GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_SUCCESS: 'GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_SUCCESS',
    GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_FAILURE: 'GET_LIST_OF_RESERVATIONS_BY_BOOK_ID_FAILURE',

    GET_LIST_OF_RESERVATIONS_BY_USER_ID_REQUEST: 'GET_LIST_OF_RESERVATIONS_BY_USER_ID_REQUEST',
    GET_LIST_OF_RESERVATIONS_BY_USER_ID_SUCCESS: 'GET_LIST_OF_RESERVATIONS_BY_USER_ID_SUCCESS',
    GET_LIST_OF_RESERVATIONS_BY_USER_ID_FAILURE: 'GET_LIST_OF_RESERVATIONS_BY_USER_ID_FAILURE',

    CREATE_RESERVATION_REQUEST: 'CREATE_RESERVATION_REQUEST',
    CREATE_RESERVATION_SUCCESS: 'CREATE_RESERVATION_SUCCESS',
    CREATE_RESERVATION_FAILURE: 'CREATE_RESERVATION_FAILURE',

    UPDATE_RESERVATION_REQUEST: 'UPDATE_RESERVATION_REQUEST',
    UPDATE_RESERVATION_SUCCESS: 'UPDATE_RESERVATION_SUCCESS',
    UPDATE_RESERVATION_FAILURE: 'UPDATE_RESERVATION_FAILURE',

    DELETE_RESERVATION_REQUEST: 'DELETE_RESERVATION_REQUEST',
    DELETE_RESERVATION_SUCCESS: 'DELETE_RESERVATION_SUCCESS',
    DELETE_RESERVATION_FAILURE: 'DELETE_RESERVATION_FAILURE'
}