export const userConstants = {
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',

    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    GET_INFO: 'GET_INFO',

    GET_BLOCKED_USERS_REQUEST: 'GET_BLOCKED_USERS_REQUEST',
    GET_BLOCKED_USERS_SUCCESS: 'GET_BLOCKED_USERS_SUCCESS',
    GET_BLOCKED_USERS_FAILURE: 'GET_BLOCKED_USERS_FAILURE',

    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    GET_CURRENT_PROFILE: 'GET_CURRENT_PROFILE',

    SET_CURRENT_USER_LOGIN: 'SET_CURRENT_USER_LOGIN',
    SET_CURRENT_USER_PASSWORD: 'SET_CURRENT_USER_PASSWORD',

    RESET: 'RESET',

    BLOCK_USER_REQUEST: 'BLOCK_USER_REQUEST',
    BLOCK_USER_SUCCESS: 'BLOCK_USER_SUCCESS',
    BLOCK_USER_FAILURE: 'BLOCK_USER_FAILURE',

    UNBLOCK_USER_REQUEST: 'UNBLOCK_USER_REQUEST',
    UNBLOCK_USER_SUCCESS: 'UNBLOCK_USER_SUCCESS',
    UNBLOCK_USER_FAILURE: 'UNBLOCK_USER_FAILURE'
}