export const userCreationConstants = {
    
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    SET_CURRENT_EMAIL: 'SET_CURRENT_EMAIL',
    SET_CURRENT_USERNAME: 'SET_CURRENT_USERNAME',
    SET_CURRENT_FIRST_NAME: 'SET_CURRENT_FIRST_NAME',
    SET_CURRENT_LAST_NAME: 'SET_CURRENT_LAST_NAME',
    SET_CURRENT_PASSWORD: 'SET_CURRENT_PASSWORD',
    SET_CURRENT_PASSWORD_CONFIRMATION: 'SET_CURRENT_PASSWORD_CONFIRMATION'
}